# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6sV3WKHtaOYZ2owV53JrKX0AvD_h8pJ
"""

import torch
print(torch.cuda.is_available())  # should print True
print(torch.cuda.get_device_name(0))  # should print Tesla T4

import yfinance as yf
import pandas as pd

# Fetch stock data with auto_adjust=False to keep Adj Close column
tesla_data = yf.download('TSLA', start='2010-01-01', auto_adjust=False)
tesla_data.columns = [col[0] if isinstance(col, tuple) else col for col in tesla_data.columns]
tesla_data['Company'] = 'Tesla'
tesla_data.to_csv('tesla_financial_data_2010_onwards.csv', index=True)

amazon_data = yf.download('AMZN', start='2010-01-01', auto_adjust=False)
amazon_data.columns = [col[0] if isinstance(col, tuple) else col for col in amazon_data.columns]
amazon_data['Company'] = 'Amazon'
amazon_data.to_csv('amazon_financial_data_2010_onwards.csv', index=True)

apple_data = yf.download('AAPL', start='2010-01-01', auto_adjust=False)
apple_data.columns = [col[0] if isinstance(col, tuple) else col for col in apple_data.columns]
apple_data['Company'] = 'Apple'
apple_data.to_csv('apple_financial_data_2010_onwards.csv', index=True)

# -*- coding: utf-8 -*-
"""Stock_trends_Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RU8YX2PwLdf8P_L3ieGMkbBoGj9QnUjt

# 1. Data Collection

## 1.1 Collecting Reddit data

FIX: pip install statements must use ! prefix in Colab notebooks,
     or be run separately in a terminal. Bare `pip install` is not valid Python.
"""

# ── INSTALL DEPENDENCIES (run these first in Colab or your terminal) ──────────
!pip install praw transformers torch pandas scikit-learn lightgbm yfinance nltk

import praw
import pandas as pd
import concurrent.futures

# Reddit API credentials
user_agent = "Scraper 1.0 by /Equivalent_Tear_6866"

reddit = praw.Reddit(
    client_id="lYVq_Wos1h8bo4CauEFVkQ",       # follow the readme file instructions
    client_secret="HRPAMddceLudjUxl8_-j1N_iSLLFyw",
    user_agent=user_agent
)

# Define companies and their related queries
stocks = {
    "Tesla": ["Tesla", "TSLA", "Model 3", "Tesla earnings", "Elon Musk"],
    "Apple": ["Apple", "AAPL", "iPhone", "Apple stock", "Apple earnings"],
    "Amazon": ["Amazon", "AMZN", "AWS", "Amazon Prime", "Amazon stock"]
}

# Define subreddits to target
subreddits = [
    "stocks", "investing", "StockMarket", "wallstreetbets",
    "personalfinance", "options", "financialindependence"
]

# Initialize a list to store posts
posts = []

# Function to fetch posts for a single query and subreddit
def fetch_posts_for_query(company, subreddit_name, query, reddit_instance):
    local_posts = []
    try:
        subreddit = reddit_instance.subreddit(subreddit_name)
        print(f"Fetching posts from r/{subreddit_name} for '{query}' ({company})...")
        for submission in subreddit.search(query, limit=1000):
            local_posts.append({
                "Company": company,
                "Subreddit": subreddit_name,
                "Query": query,
                "Title": submission.title,
                "Text": submission.selftext,
                "Score": submission.score,
                "Comments": submission.num_comments,
                "Timestamp": submission.created_utc
            })
    except Exception as e:
        print(f"Error fetching posts for {company}, r/{subreddit_name}, '{query}': {e}")
    return local_posts

# Use ThreadPoolExecutor for parallel processing
with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    future_to_posts = {
        executor.submit(fetch_posts_for_query, company, subreddit_name, query, reddit)
        for company, queries in stocks.items()
        for subreddit_name in subreddits
        for query in queries
    }
    for future in concurrent.futures.as_completed(future_to_posts):
        try:
            result_posts = future.result()
            posts.extend(result_posts)
        except Exception as exc:
            print(f'Generated an exception: {exc}')

# Convert the list of posts into a DataFrame
df = pd.DataFrame(posts)

# Save raw data to a CSV file
df.to_csv("stock_data_raw.csv", index=False)
print(f"Scraped data saved successfully. Total rows: {len(df)}")

df.shape
df.columns
df.head()
df.info()


# =============================================================================
# 2. Data Preprocessing
# =============================================================================

# 2.1 Data Cleaning - removing duplicates, drop null

import pandas as pd

df = pd.read_csv("stock_data_raw.csv")
print(df.head())
print(df.info())

# Check for Duplicates and Missing Values
print("Duplicates:", df.duplicated().sum())
print("Null Values:\n", df.isnull().sum())

# Fill null 'Text' values with corresponding 'Title' values
df['Text'] = df.apply(lambda row: row['Title'] if pd.isnull(row['Text']) else row['Text'], axis=1)

df.duplicated().sum()
len(df['Title'].unique())

# Check for duplicates in the 'Text' and 'Title' columns
print("Before removing duplicates:")
print(df.duplicated(subset=["Title", "Text"]).sum())

df = df.drop_duplicates(subset=["Title", "Text"])

# Time and Date Analysis
df["Date"] = pd.to_datetime(df["Timestamp"], unit="s").dt.date
df.drop(columns=["Timestamp"], inplace=True)

# Group by company and find the date range
date_ranges = df.groupby('Company')['Date'].agg(['min', 'max'])
print(date_ranges)

# Save the Cleaned dataset
df.to_csv("stock_cleaned.csv", index=False)
print("Cleaned data saved successfully!")


# =============================================================================
# 2.2 Data Preprocessing for Sentiment Analysis
# =============================================================================

import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')
nltk.download('wordnet')
nltk.download('punkt_tab')

# FIX: removed hardcoded /content/ path — use relative path so it works
#      both locally and in Colab (Colab's working dir is /content by default)
df = pd.read_csv('stock_cleaned.csv')

# Removing URLs and Special Characters
def clean_text(text):
    text = str(text)  # FIX: guard against non-string values causing AttributeError
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    return text.lower()

df["Cleaned_Text"] = df["Text"].apply(clean_text)

# Removing Stop-Words
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in stop_words])

df["Cleaned_Text"] = df["Cleaned_Text"].apply(remove_stopwords)

# Tokenization and Lemmatization
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["Cleaned_Text"] = df["Cleaned_Text"].apply(lemmatize_text)

df.isnull().sum()

df.to_csv("stock_preprocessed.csv", index=False)
print("Preprocessed data saved successfully!")


# =============================================================================
# Sentiment Analysis
# FIX: removed bare `pip install` line — install commands are not valid Python
#      Run: !pip install transformers torch pandas scikit-learn  (in Colab)
#      or:   pip install transformers torch pandas scikit-learn  (in terminal)
# =============================================================================

from transformers import BertTokenizer, BertForSequenceClassification
import torch
from torch.utils.data import DataLoader, Dataset

# Load FinBERT model and tokenizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = BertTokenizer.from_pretrained("yiyanghkust/finbert-tone")
model = BertForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone")
model.to(device)
model.eval()

# Custom Dataset for DataLoader
class TextDataset(Dataset):
    def __init__(self, texts):
        self.texts = texts

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return self.texts[idx]

# Function to process a batch
def process_batch(text_batch):
    inputs = tokenizer(list(text_batch), return_tensors="pt", truncation=True, max_length=512, padding=True)
    inputs = {key: val.to(device) for key, val in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
        sentiments = torch.argmax(probs, axis=1)
    return sentiments, probs

# Load preprocessed data
df = pd.read_csv("stock_preprocessed.csv")
texts = df["Text"].fillna("").astype(str).tolist()

# Batch processing
batch_size = 32
dataloader = DataLoader(TextDataset(texts), batch_size=batch_size)

sentiments, sentiment_scores = [], []
for batch in dataloader:
    batch_sentiments, batch_probs = process_batch(batch)
    sentiments.extend(batch_sentiments.cpu().numpy())
    sentiment_scores.extend(batch_probs.max(dim=1).values.cpu().numpy())

# Map numerical sentiments back to labels
sentiment_labels = ["Positive", "Neutral", "Negative"]
df["Sentiment"] = [sentiment_labels[s] for s in sentiments]
df["Sentiment_Score"] = sentiment_scores

df.to_csv("stock_data_with_sentiment.csv", index=False)
print("Sentiment analysis completed and saved.")

df.head()


# =============================================================================
# 3. Feature Engineering
# =============================================================================

import matplotlib.pyplot as plt

# FIX: removed hardcoded /content/ path
df = pd.read_csv("stock_data_with_sentiment.csv")

# Visualise sentiment distribution
sentiment_counts = df['Sentiment'].value_counts()
plt.figure(figsize=(8, 6))
plt.bar(sentiment_counts.index, sentiment_counts.values, color=['green', 'blue', 'red'])
plt.title('Sentiment Analysis of Stock Data')
plt.xlabel('Sentiment')
plt.ylabel('Number of Posts')
plt.show()

df = df.drop(['Subreddit', 'Query', 'Title', 'Text'], axis=1)

# Group by Company and count Sentiments
sentiment_counts = df.groupby("Company")["Sentiment"].value_counts().unstack(fill_value=0)
sentiment_counts = sentiment_counts.reset_index()
print(sentiment_counts)


# =============================================================================
# 3.1 Load Stock Price Data
# =============================================================================

import yfinance as yf

# Fetch and save Tesla data
tesla_data = yf.download('TSLA', start='2010-01-01')
tesla_data['Company'] = 'Tesla'
tesla_data.to_csv('tesla_financial_data_2010_onwards.csv', index=True)
print(tesla_data.head())

# Fetch and save Amazon data
amazon_data = yf.download('AMZN', start='2010-01-01')
amazon_data['Company'] = 'Amazon'
amazon_data.to_csv('amazon_financial_data_2010_onwards.csv', index=True)
print(amazon_data.head())

# Fetch and save Apple data
apple_data = yf.download('AAPL', start='2010-01-01')
apple_data['Company'] = 'Apple'
apple_data.to_csv('apple_financial_data_2010_onwards.csv', index=True)
print(apple_data.head())


# =============================================================================
# 3.2 Prepare Stock Price Data
#
# FIX: The original code had a broken rename: it renamed 'Date' -> 'Price' then
#      tried to read 'Price' back as a date — this KeyError caused the crash.
#      Also removed fragile iloc[2:] row-dropping in favour of explicitly
#      parsing the Date column and dropping rows where it's not a valid date
#      (handles yfinance header artifacts regardless of version).
# =============================================================================

def load_and_clean_stock_csv(filepath):
    data = pd.read_csv(filepath)
    # The first column is always the date index saved by yfinance; rename it safely
    data.rename(columns={data.columns[0]: 'Date'}, inplace=True)
    # Parse dates; coerce errors turns non-date rows (yfinance header artifacts) into NaT
    data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
    # Drop rows where Date couldn't be parsed (e.g. the extra header rows yfinance adds)
    data.dropna(subset=['Date'], inplace=True)
    data['Date'] = data['Date'].dt.date
    data.reset_index(drop=True, inplace=True)
    return data

tesla_data  = load_and_clean_stock_csv('tesla_financial_data_2010_onwards.csv')
amazon_data = load_and_clean_stock_csv('amazon_financial_data_2010_onwards.csv')
apple_data  = load_and_clean_stock_csv('apple_financial_data_2010_onwards.csv')

# Concatenate all companies into one DataFrame
all_data = pd.concat([tesla_data, amazon_data, apple_data])
all_data.reset_index(drop=True, inplace=True)

all_data.to_csv('all_companies_financial_data_cleaned.csv', index=False)
print(all_data.sample(5))
all_data.info()

# Convert columns to proper numeric types
all_data = pd.read_csv('all_companies_financial_data_cleaned.csv')
all_data['Date'] = pd.to_datetime(all_data['Date'])

for col in ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']:
    all_data[col] = pd.to_numeric(all_data[col], errors='coerce')

print(all_data.dtypes)
all_data.to_csv('all_companies_financial_data_cleaned_with_types.csv', index=False)
print(all_data.head())


# =============================================================================
# 3.3 Combine Sentiment and Stock Price Data
# =============================================================================

all_data = pd.read_csv('all_companies_financial_data_cleaned_with_types.csv')
all_data['Date'] = pd.to_datetime(all_data['Date'])
all_data = all_data.sort_values(by='Date')

# Classification target: +1 price up, -1 price down, 0 unchanged
all_data['Price Change'] = all_data['Close'].shift(-1) - all_data['Close']
all_data['Target'] = all_data['Price Change'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else 0))
all_data = all_data.drop(columns=['Price Change'])

print(all_data[['Date', 'Company', 'Close', 'Target']].head())
all_data.to_csv('all_companies_classification_data.csv', index=False)
print(all_data.dtypes)

# Merge stock data with sentiment data
stock_data = pd.read_csv('all_companies_classification_data.csv')

# FIX: reload sentiment df explicitly from CSV rather than relying on the `df`
#      variable still being in scope (it may have been overwritten above)
sentiment_data = pd.read_csv('stock_data_with_sentiment.csv')

stock_data['Date']     = pd.to_datetime(stock_data['Date'])
sentiment_data['Date'] = pd.to_datetime(sentiment_data['Date'])

merged_data = pd.merge(stock_data, sentiment_data, on=['Company', 'Date'], how='inner')
print(merged_data.head())
merged_data.to_csv('merged_stock_sentiment_data.csv', index=False)


# =============================================================================
# 3.4 Feature Analysis of merged data
# =============================================================================

merged_data.info()
merged_data['Sentiment'].value_counts()
merged_data.shape

# 3.5 Save the merged file
merged_data.to_csv('merged_stock_sentiment_data.csv', index=False)


# =============================================================================
# 4. Modeling Preparation
# =============================================================================

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
import lightgbm as lgb

# 4.2 Train-test split
data = pd.read_csv('merged_stock_sentiment_data.csv')

X = data.drop(columns=['Target'])
y = data['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Features: {X_train.shape}, Training Target: {y_train.shape}")
print(f"Testing Features: {X_test.shape}, Testing Target: {y_test.shape}")


# 4.3 Preprocessing Pipeline
numeric_features     = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume', 'Sentiment_Score']
categorical_features = ['Company', 'Sentiment']

numeric_transformer = make_pipeline(
    SimpleImputer(strategy='mean'),
    StandardScaler()
)

categorical_transformer = make_pipeline(
    SimpleImputer(strategy='constant', fill_value='missing'),
    OneHotEncoder(handle_unknown='ignore')
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])


# =============================================================================
# 5. Model Training and Evaluation
# =============================================================================

# 5.1 Define models
models = {
    'Logistic Regression':  LogisticRegression(),
    'Random Forest':        RandomForestClassifier(),
    'Gradient Boosting':    GradientBoostingClassifier(),
    'SVM':                  SVC(),
    'LightGBM':             lgb.LGBMClassifier()
}

# 5.2 Hyperparameter grids
param_grids = {
    'Logistic Regression': {
        'logisticregression__C':      [0.01, 0.1, 1, 10],
        'logisticregression__solver': ['liblinear', 'lbfgs']
    },
    'Random Forest': {
        'randomforestclassifier__n_estimators': [100, 200],
        'randomforestclassifier__max_depth':    [5, 10, 15]
    },
    'Gradient Boosting': {
        'gradientboostingclassifier__n_estimators':  [100, 200],
        'gradientboostingclassifier__learning_rate': [0.01, 0.1, 0.5]
    },
    'SVM': {
        'svc__C':      [0.1, 1, 10],
        'svc__kernel': ['linear', 'rbf']
    },
    'LightGBM': {
        'lgbmclassifier__n_estimators':  [100, 200],
        'lgbmclassifier__learning_rate': [0.01, 0.1, 0.3],
        'lgbmclassifier__max_depth':     [3, 5, 7],
        'lgbmclassifier__num_leaves':    [31, 50]
    }
}

# 5.3 Train and evaluate
results    = {}
best_model = None
best_score = 0

for model_name, model in models.items():
    print(f"Training {model_name}...")

    pipeline    = make_pipeline(preprocessor, model)
    grid_search = GridSearchCV(pipeline, param_grids[model_name], cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    results[model_name] = {
        'Best Params': grid_search.best_params_,
        'Best Score':  grid_search.best_score_
    }

    if grid_search.best_score_ > best_score:
        best_score = grid_search.best_score_
        best_model = grid_search.best_estimator_

    y_pred = grid_search.best_estimator_.predict(X_test)
    results[model_name]['Classification Report'] = classification_report(y_test, y_pred)
    results[model_name]['Accuracy']              = accuracy_score(y_test, y_pred)

for model_name, result in results.items():
    print(f"\n{model_name} Results:")
    print(f"Best Params: {result['Best Params']}")
    print(f"Best Cross-Validation Score: {result['Best Score']}")
    print(f"Accuracy: {result['Accuracy']}")
    print(f"Classification Report:\n{result['Classification Report']}")


# 5.4 Best Model
print("\nBest Model:")
print(f"Model: {best_model}")
print(f"Best Cross-Validation Score: {best_score}")
print("Classification Report:")
y_pred_best = best_model.predict(X_test)
print(classification_report(y_test, y_pred_best))

# =============================================================================
# 3.2 Prepare Stock Price Data
#
# FIX: The original code had a broken rename: it renamed 'Date' -> 'Price' then
#      tried to read 'Price' back as a date — this KeyError caused the crash.
#      Also removed fragile iloc[2:] row-dropping in favour of explicitly
#      parsing the Date column and dropping rows where it's not a valid date
#      (handles yfinance header artifacts regardless of version).
# =============================================================================

def load_and_clean_stock_csv(filepath):
    data = pd.read_csv(filepath, header=0)
    # Flatten any multi-level column headers yfinance creates
    data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]
    # Rename first column to Date safely
    data.rename(columns={data.columns[0]: 'Date'}, inplace=True)
    # Parse dates, coerce errors drops junk header rows
    data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
    data.dropna(subset=['Date'], inplace=True)
    data['Date'] = data['Date'].dt.date
    data.reset_index(drop=True, inplace=True)
    return data

tesla_data  = load_and_clean_stock_csv('tesla_financial_data_2010_onwards.csv')
amazon_data = load_and_clean_stock_csv('amazon_financial_data_2010_onwards.csv')
apple_data  = load_and_clean_stock_csv('apple_financial_data_2010_onwards.csv')

# Concatenate all companies into one DataFrame
all_data = pd.concat([tesla_data, amazon_data, apple_data])
all_data.reset_index(drop=True, inplace=True)

all_data.to_csv('all_companies_financial_data_cleaned.csv', index=False)
print(all_data.sample(5))
all_data.info()

# Convert columns to proper numeric types
all_data = pd.read_csv('all_companies_financial_data_cleaned.csv')
all_data['Date'] = pd.to_datetime(all_data['Date'])

for col in ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']:
    all_data[col] = pd.to_numeric(all_data[col], errors='coerce')

print(all_data.dtypes)
all_data.to_csv('all_companies_financial_data_cleaned_with_types.csv', index=False)
print(all_data.head())


# =============================================================================
# 3.3 Combine Sentiment and Stock Price Data
# =============================================================================

all_data = pd.read_csv('all_companies_financial_data_cleaned_with_types.csv')
all_data['Date'] = pd.to_datetime(all_data['Date'])
all_data = all_data.sort_values(by='Date')

# Classification target: +1 price up, -1 price down, 0 unchanged
all_data['Price Change'] = all_data['Close'].shift(-1) - all_data['Close']
all_data['Target'] = all_data['Price Change'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else 0))
all_data = all_data.drop(columns=['Price Change'])

print(all_data[['Date', 'Company', 'Close', 'Target']].head())
all_data.to_csv('all_companies_classification_data.csv', index=False)
print(all_data.dtypes)

# Merge stock data with sentiment data
stock_data = pd.read_csv('all_companies_classification_data.csv')

# FIX: reload sentiment df explicitly from CSV rather than relying on the `df`
#      variable still being in scope (it may have been overwritten above)
sentiment_data = pd.read_csv('stock_data_with_sentiment.csv')

stock_data['Date']     = pd.to_datetime(stock_data['Date'])
sentiment_data['Date'] = pd.to_datetime(sentiment_data['Date'])

merged_data = pd.merge(stock_data, sentiment_data, on=['Company', 'Date'], how='inner')
print(merged_data.head())
merged_data.to_csv('merged_stock_sentiment_data.csv', index=False)


# =============================================================================
# 3.4 Feature Analysis of merged data
# =============================================================================

merged_data.info()
merged_data['Sentiment'].value_counts()
merged_data.shape

# 3.5 Save the merged file
merged_data.to_csv('merged_stock_sentiment_data.csv', index=False)


# =============================================================================
# 4. Modeling Preparation
# =============================================================================

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
import lightgbm as lgb

# 4.2 Train-test split
data = pd.read_csv('merged_stock_sentiment_data.csv')

X = data.drop(columns=['Target'])
y = data['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Features: {X_train.shape}, Training Target: {y_train.shape}")
print(f"Testing Features: {X_test.shape}, Testing Target: {y_test.shape}")


# 4.3 Preprocessing Pipeline
numeric_features     = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume', 'Sentiment_Score']
categorical_features = ['Company', 'Sentiment']

numeric_transformer = make_pipeline(
    SimpleImputer(strategy='mean'),
    StandardScaler()
)

categorical_transformer = make_pipeline(
    SimpleImputer(strategy='constant', fill_value='missing'),
    OneHotEncoder(handle_unknown='ignore')
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])


# =============================================================================
# 5. Model Training and Evaluation
# =============================================================================

# 5.1 Define models
models = {
    'Logistic Regression':  LogisticRegression(),
    'Random Forest':        RandomForestClassifier(),
    'Gradient Boosting':    GradientBoostingClassifier(),
    'SVM':                  SVC(),
    'LightGBM':             lgb.LGBMClassifier()
}

# 5.2 Hyperparameter grids
param_grids = {
    'Logistic Regression': {
        'logisticregression__C':      [0.01, 0.1, 1, 10],
        'logisticregression__solver': ['liblinear', 'lbfgs']
    },
    'Random Forest': {
        'randomforestclassifier__n_estimators': [100, 200],
        'randomforestclassifier__max_depth':    [5, 10, 15]
    },
    'Gradient Boosting': {
        'gradientboostingclassifier__n_estimators':  [100, 200],
        'gradientboostingclassifier__learning_rate': [0.01, 0.1, 0.5]
    },
    'SVM': {
        'svc__C':      [0.1, 1, 10],
        'svc__kernel': ['linear', 'rbf']
    },
    'LightGBM': {
        'lgbmclassifier__n_estimators':  [100, 200],
        'lgbmclassifier__learning_rate': [0.01, 0.1, 0.3],
        'lgbmclassifier__max_depth':     [3, 5, 7],
        'lgbmclassifier__num_leaves':    [31, 50]
    }
}

# 5.3 Train and evaluate
results    = {}
best_model = None
best_score = 0

for model_name, model in models.items():
    print(f"Training {model_name}...")

    pipeline    = make_pipeline(preprocessor, model)
    grid_search = GridSearchCV(pipeline, param_grids[model_name], cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    results[model_name] = {
        'Best Params': grid_search.best_params_,
        'Best Score':  grid_search.best_score_
    }

    if grid_search.best_score_ > best_score:
        best_score = grid_search.best_score_
        best_model = grid_search.best_estimator_

    y_pred = grid_search.best_estimator_.predict(X_test)
    results[model_name]['Classification Report'] = classification_report(y_test, y_pred)
    results[model_name]['Accuracy']              = accuracy_score(y_test, y_pred)

for model_name, result in results.items():
    print(f"\n{model_name} Results:")
    print(f"Best Params: {result['Best Params']}")
    print(f"Best Cross-Validation Score: {result['Best Score']}")
    print(f"Accuracy: {result['Accuracy']}")
    print(f"Classification Report:\n{result['Classification Report']}")


# 5.4 Best Model
print("\nBest Model:")
print(f"Model: {best_model}")
print(f"Best Cross-Validation Score: {best_score}")
print("Classification Report:")
y_pred_best = best_model.predict(X_test)
print(classification_report(y_test, y_pred_best))

from google.colab import files
files.download('merged_stock_sentiment_data.csv')
files.download('stock_data_with_sentiment.csv')
files.download('all_companies_classification_data.csv')